# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

censoring_impl <- function(data, thr_or_null, uncertain_or_null, missing_or_null, sigma, nns_or_null, callback) {
    .Call('destiny_censoring_impl', PACKAGE = 'destiny', data, thr_or_null, uncertain_or_null, missing_or_null, sigma, nns_or_null, callback)
}

predict_censoring_impl <- function(data, data2, thr, uncertain, missing, sigma) {
    .Call('destiny_predict_censoring_impl', PACKAGE = 'destiny', data, data2, thr, uncertain, missing, sigma)
}

d2_no_censor <- function(nn_index, nn_dist, callback) {
    .Call('destiny_d2_no_censor', PACKAGE = 'destiny', nn_index, nn_dist, callback)
}

icor2_no_censor <- function(nn_index, imputed_data, callback, use_rank = FALSE) {
    .Call('destiny_icor2_no_censor', PACKAGE = 'destiny', nn_index, imputed_data, callback, use_rank)
}

