# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

censoring_impl <- function(data, sigmas, dists, thr_or_null, uncertain_or_null, missing_or_null, callback) {
    .Call('destiny_censoring_impl', PACKAGE = 'destiny', data, sigmas, dists, thr_or_null, uncertain_or_null, missing_or_null, callback)
}

predict_censoring_impl <- function(data, data2, thr, uncertain, missing, sigma) {
    .Call('destiny_predict_censoring_impl', PACKAGE = 'destiny', data, data2, thr, uncertain, missing, sigma)
}

icor2_no_censor <- function(dists, imputed_data, callback, use_rank = FALSE) {
    .Call('destiny_icor2_no_censor', PACKAGE = 'destiny', dists, imputed_data, callback, use_rank)
}

